<?='<?xml version="1.0" encoding="UTF-8"?>' /* @var $viewData FormViewData*/  ?>
<vxml version="2.1" xml:lang="<?= $viewData->getLanguage()?>">
	<form id="MainMenu">
		<field name="<?=$viewData->getVarReturnedName()?>">
			<prompt>
				<?=$viewData->getPrompt(); ?>
				<? if ($viewData->existsPreviousPageLink()) { ?>
					<?= $viewData->getPreviousPagePrompt(); ?>
				<? } ?>

				<? if ($viewData->existsMainMenuLink()) { ?>
					<?= $viewData->getMainMenuPrompt()
					; ?>
				<? } ?>
			</prompt>

			<?= $viewData->getGrammar(); ?>

			<noinput>
				Lo siento, no he entendido lo que ha dicho. Por favor intentelo de nuevo.
				<reprompt/>
			</noinput>

			<nomatch>
				Lo siento, no he entendido lo que ha dicho. Por favor intentelo de nuevo.
				<reprompt/>
			</nomatch>

		</field>

		<filled>
				<?if ($viewData->existsMainMenuLink()) { ?>
					<if cond="<?=$viewData->getVarReturnedName()?> == <?=KeyPhone::toDigit($viewData->getMainMenuOption()) ?>">
						<prompt>Has elegido Volver al menú principal.</prompt>
						<submit next="<?= $viewData->getMainMenuLink()->getHrefForRender() ?>"   />
					</if>
				<?}?>
				<?if ($viewData->existsPreviousPageLink()) { ?>
					<if cond="<?=$viewData->getVarReturnedName()?> == '<?=KeyPhone::toDigit($viewData->getPreviousPageOption()) ?>'">
						<prompt>Has elegido volver a la página anterior ?> </prompt>
						<submit next="<?= $viewData->getPreviousPageLink()->getHrefForRender() ?>" />
					</if>
				<?}?>

				<prompt>Has dicho <value expr="<?=$viewData->getVarReturnedName()?>"/></prompt>
				<submit next="<?=$viewData->getSubmitLink()->getHrefForRender()?>" method="post" namelist="<?=$viewData->getVarReturnedName()?>" />
		</filled>
	</form>
</vxml>