<?='<?xml version="1.0" encoding="UTF-8"?>' /* @var $viewData FormViewData*/  ?>
<vxml version="2.1" xml:lang="<?= $viewData->getLanguage()?>">
	<?foreach($viewData->getHiddenParams() as $hiddenParamName => $value) {?>
		<var name="<?=$hiddenParamName?>" expr="'<?=$value?>'"/>
	<?}?>
	<form id="MainMenu">
		<field name="<?=$viewData->getVarReturnedName()?>">
			<?= $viewData->getGrammar(); ?>

			<prompt bargeintype="hotword">
				<?=$viewData->getPrompt(); ?>
				<? if ($viewData->existsPreviousPageLink()) { ?>
					<?= $viewData->getPreviousPagePrompt(); ?>
				<? } ?>

				<? if ($viewData->existsMainMenuLink()) { ?>
					<?= $viewData->getMainMenuPrompt(); ?>
				<? } ?>
			</prompt>

			<noinput>
				Lo siento, no he entendido lo que ha dicho. Por favor intentelo de nuevo.
				<reprompt/>
			</noinput>

			<nomatch>
				Lo siento, no he entendido lo que ha dicho. Por favor intentelo de nuevo.
				<reprompt/>
			</nomatch>

		</field>

		<filled mode="all">
				<?if ($viewData->existsMainMenuLink()) { ?>
					<if cond="<?=$viewData->getVarReturnedName()?> == <?=KeyPhone::toDigit($viewData->getMainMenuOption()) ?>">
						<prompt>Has elegido Volver al menú principal.</prompt>
						<submit next="<?= $viewData->getMainMenuLink()->getHrefForRender() ?>" method="post" namelist="<?=$viewData->getNameList()?>" />
					</if>
				<?}?>
				<?if ($viewData->existsPreviousPageLink()) { ?>
					<if cond="<?=$viewData->getVarReturnedName()?> == '<?=KeyPhone::toDigit($viewData->getPreviousPageOption()) ?>'">
						<prompt>Has elegido volver a la página anterior ?> </prompt>
						<submit next="<?= $viewData->getPreviousPageLink()->getHrefForRender() ?>" method="post" namelist="<?=$viewData->getNameList()?>" />
					</if>
				<?}?>
				<?if (!$viewData->isHiddenOption()) { ?>
					<prompt>Has dicho <value expr="<?=$viewData->getVarReturnedName()?>"/></prompt>
				<?}?>
				<submit next="<?=$viewData->getSubmitLink()->getHrefForRender()?>" method="post" namelist="<?=$viewData->getNameList()?>" />
		</filled>
	</form>
</vxml>